"""Original launch drafts; source-specific summaries remain deliberately brief."""

ARTICLES = [
    {
        "slug": "what-is-molecular-hydrogen",
        "title": "What is molecular hydrogen? A plain-language introduction",
        "category": "THE BASICS",
        "image": "/static/h24you/water-placeholder.webp",
        "references": [0, 1],
        "parts": [
            ("Start with a very small question.", "What do we mean when we talk about hydrogen water? The name can sound as though someone has changed water into something entirely new. A clearer starting point is much simpler: water can contain dissolved molecular hydrogen. That description tells us what is being discussed. It does not, by itself, tell us what drinking it will do. Keeping those two questions separate makes the whole subject easier to explore.\n\nYou do not need a science degree to begin. You need a few useful distinctions, a willingness to follow the source, and room for an answer that is still developing. This introduction is a map for that reading, rather than a promise about a product."),
            ("H₂ and H₂O are different things.", "Hydrogen is an element. Molecular hydrogen is a pair of hydrogen atoms joined together, written H₂. Water is a different molecule, written H₂O: its hydrogen atoms are bonded with oxygen. When researchers discuss hydrogen-rich water, they are talking about molecular hydrogen dissolved in water, not about removing the oxygen from the water molecule.\n\nThat distinction matters when comparing descriptions online. A product name, a description of how water was prepared, and a measured amount of dissolved hydrogen are different pieces of information. A useful explanation should make clear which one it is giving you. If a claim jumps between them without explanation, slow down and look for the missing detail."),
            ("One subject, many research approaches.", "Two early reviews offer useful historical starting points. Dixon and colleagues published an overview in 2013, while Ichihara and colleagues reviewed a broad body of literature in 2015. These papers bring together different research approaches. They are not trials of H2 4 You products, and they should not be described that way.\n\nWhen opening either paper, notice the setting and method behind each example. Research in a laboratory, work involving animals, and studies involving people answer different questions. Likewise, studying hydrogen through one method of administration does not automatically establish what happens with another. A review can help you see the landscape, but it cannot make all those differences disappear."),
            ("Read the nouns before the headline.", "A practical reading habit is to underline the specific things being described. Who took part? What was prepared? What was compared? What was measured? These questions are more useful than asking whether a headline sounds exciting. They turn a broad statement into something you can actually examine.\n\nThen look for the authors' limitations. Perhaps an experiment was short, the group was small, or the measurement was a laboratory marker rather than an everyday experience. Those details do not make a paper uninteresting. They describe the size and shape of the question it can answer. Good science becomes more useful when its boundaries stay visible."),
            ("Curiosity does not need a shortcut.", "It is easy to turn a growing research field into a shopping checklist: more papers, stronger language, bigger promises. A more helpful approach is to keep the research and the retail product distinct. The existence of published research does not establish that a particular tablet or bottle produces a particular outcome. Product-specific information needs its own evidence and accurate labeling.\n\nThe same care applies to numbers. A count of articles is a count of publications, not a count of established benefits. It may include different types of research and different methods. Before sharing a number, ask what the database counted and when the figure was checked. Context belongs beside the number, not hidden elsewhere."),
            ("Your next good question.", "Start with one paper from the references below. Read its purpose, then its methods, then its conclusion. Write down one thing it examined and one thing it did not establish. You will have a more useful understanding than a headline alone can offer.\n\nOur invitation is to stay curious without rushing to certainty. Molecular hydrogen is a subject you can explore one clear question at a time. We will keep linking to original sources and distinguishing research from product information as this journal develops. This article is an educational draft for review, and it does not provide instructions for treating a health condition."),
        ],
    },
    {
        "slug": "timing-and-consistency",
        "title": "Timing and consistency: how hydrogen water is used in studies",
        "category": "READING THE METHODS",
        "image": "/static/h24you/tablets-placeholder.webp",
        "references": [2, 3],
        "parts": [
            ("A routine is not a research protocol.", "The question often starts in an ordinary place: morning, afternoon, or after a workout? Before looking for the perfect time, it helps to understand what a study's schedule actually means. Researchers choose timing to investigate a defined question under particular conditions. That schedule describes the experiment. It is not automatically a daily recommendation for everyone reading about it.\n\nThis matters because the appeal of a simple routine can make a complicated result sound universal. A paper might examine a single exercise session, a specific group of participants, and a carefully timed measurement. Turning that into a broad rule for everyday use would add a claim that the study may never have tested."),
            ("What the two references can show you.", "LeBaron and colleagues' 2019 paper describes a randomized, double-blind, placebo-controlled crossover pilot study of acute supplementation and submaximal exercise. Mikami and colleagues' 2019 paper examines hydrogen water in relation to exercise measurements using controlled comparisons. They provide examples of how investigators organize a question around an activity.\n\nRead each original paper for its own protocol. Do not blend their schedules into a new set of product directions. The references are included to help you inspect study design, not to claim that H2 4 You tablets or bottles reproduce either experiment. The products used, participants, preparation and measurements all matter when making that distinction."),
            ("Build a simple methods checklist.", "When you open a study, create four short notes: participants, preparation, timing, and measurement. Under participants, record the group actually studied. Under preparation, note what the researchers administered and how it was described. Under timing, separate when the intervention happened from when the outcome was measured. Under measurement, write the exact outcome the authors assessed.\n\nThis small exercise often reveals why two papers that sound similar are not directly comparable. One might assess a short-term response around a single activity; another might use a different schedule or a different outcome. Comparing the headlines skips the very details that make the experiments meaningful."),
            ("Consistency helps a comparison make sense.", "In research, consistency means following the planned method closely enough that the comparison can be interpreted. It can involve using the same preparation procedure, taking measurements at specified times, or recording whether participants followed the instructions. It does not mean that repeating a consumer habit must eventually produce a particular result.\n\nLook for how the paper handles variation. Were the conditions described clearly? Was there a comparison group or comparison period? Did the authors report missing information? A schedule is useful only as part of the wider method. Even a carefully repeated procedure still has to be interpreted alongside the study's design and limitations."),
            ("Separate experience from measurement.", "A pleasant daily ritual and a measured research outcome belong to different conversations. You can enjoy taking a pause for water without using that experience as evidence that a particular biological effect occurred. Equally, a change in one study measurement does not explain every feeling a person might report after trying a new routine.\n\nWhen reading, ask whether the outcome was an instrument reading, a performance test, a questionnaire, or something else. Then ask whether the difference mattered in the context of the experiment. Keeping these distinctions visible helps avoid turning a narrow observation into a much larger story than the data support."),
            ("Bring that care back to everyday use.", "For a consumer product, the appropriate starting point is its confirmed label and user manual. Research schedules should not replace the supplied instructions. For H2 4 You, final tablet directions, ingredients and pack details are still awaiting confirmation in this preview. We will not fill those gaps by combining methods from unrelated studies.\n\nIf you want to understand timing better, choose one of the references and read the methods section before the conclusion. Notice how much detail sits between the question and the result. That detail is the point: a study tells you what happened under its conditions. It leaves other questions open, including how broadly the findings apply. This article remains a draft for editorial review."),
        ],
    },
    {
        "slug": "how-to-read-hydrogen-research",
        "title": "How to read hydrogen research: what is studied and what is still unknown",
        "category": "A CURIOUS MIND",
        "image": "/static/h24you/bottle-placeholder.webp",
        "references": [4, 5, 6],
        "parts": [
            ("Start with the question, not the promise.", "A research paper is an attempt to answer a question. Before deciding what you think about its conclusion, find that question and make it specific. Who or what was studied? What was compared? Which outcome mattered to the researchers? A clear answer to those questions gives you a better starting point than an enthusiastic summary on a product page.\n\nThis is especially useful when a field contains different methods and many kinds of outcomes. Papers can share the words molecular hydrogen while addressing very different questions. Reading them carefully means preserving those differences rather than gathering every positive-sounding sentence into one large claim."),
            ("Know what kind of paper you opened.", "An individual study reports its own investigation. A systematic review uses a stated process to find and assess studies relevant to a question. A meta-analysis may combine numerical results when the data and methods allow it. These are different ways of learning from evidence, and each needs careful reading.\n\nA larger collection of papers does not automatically remove weaknesses in the original work. The value of a review depends partly on what it includes, what it leaves out, and how it handles differences between studies. Look for those decisions. They tell you what the pooled conclusion is actually describing."),
            ("Three examples, three reading exercises.", "Li and colleagues' 2024 systematic review and meta-analysis examines exercise-induced oxidative stress in healthy adults. Zhou and colleagues' 2023 review considers fatigue and aerobic capacity. Todorovic and colleagues' 2023 systematic review concerns hydrogen-rich water and blood lipid profiles. Their subjects are related, but their outcomes are not interchangeable.\n\nUse the references to practice identifying those boundaries. A review about one outcome cannot stand in for evidence about another. None of these citations should be presented as a trial of H2 4 You products. The papers are linked so readers can inspect the research itself, including the authors' methods and caveats."),
            ("Look at people, comparisons and uncertainty.", "First, check who took part in the included studies. An observation in one group may not apply to another group. Next, look at the comparison: what did the other participants or study periods receive? Without that context, a change over time can be easy to misread. Finally, ask how much uncertainty surrounds the estimate.\n\nYou do not need to calculate the statistics yourself to notice whether the authors describe a result as uncertain, limited, or inconsistent. Read the discussion alongside the numerical results. If a summary sounds more certain than the paper, return to the original wording and the actual question being tested."),
            ("A measured marker is not the whole story.", "Researchers may study a laboratory measurement, a reported experience, or a performance outcome. These can all be interesting, but they represent different things. A change in a marker should not quietly become a claim about how someone will feel, how a product will perform, or what will happen over a longer period.\n\nAsk what would need to be measured to support the next step in the argument. If an experiment was short, a long-term claim needs additional evidence. If different preparations were used across studies, a specific retail product needs its own support. This habit keeps an appealing explanation from outrunning the information available."),
            ("Leave room for an unfinished answer.", "A useful conclusion can be that the evidence is interesting and more research is needed. That is not a failure to choose a side. It is an accurate way to describe a question that has not been settled. Good reading allows encouraging findings and meaningful limitations to exist in the same paragraph.\n\nFor your next paper, write three sentences: what the researchers asked, what the design allowed them to examine, and what remains unknown. Keep product promises out of those sentences unless the exact product and claim were tested. You will end up with a clearer account that is easier to share responsibly. Our Science library is designed for this kind of exploration, and this article remains an educational draft awaiting review."),
        ],
    },
]
